{{- range $path, $_ := .Values.binaryData }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $path | printf "%s-%s-bd" (include "app.fullname" $) | include "normalize.name" }}
binaryData:
{{- range $name, $file := $_ }}
  {{ $name }}: {{ $file | indent 4 }}
{{ end }}
{{ end }}