{{- range $path, $_ := .Values.files }}
  {{- with $_ }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" $ }}{{ regexReplaceAll "\\W+" $path "-" }}
data:
    {{- range $name, $file := . }}
  {{ $name }}: | 
{{ $file | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}