{{- range $path, $_ := .Values.file }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $path | printf "%s-%s" (include "app.fullname" $) | include "normalize.name" }}
data:
{{- range $name, $file := $_ }}
  {{ $name }}: | 
{{ $file | indent 4 }}
{{ end }}
{{ end }}