{{- range $path, $_ := .Values.files }}
  {{- with $_ }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $path | printf "%s-%s" (include "app.fullname" $) | include "normalize.name" }}
data:
    {{- range $name, $file := . }}
  {{ $name }}: | 
{{ $file | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}