{{- if not .Values.serviceDisable }}
{{- $s := .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
{{- with $s.annotations }}
{{ toYaml . | nindent 4 }}
{{- end }}
    {{- include "app.annotations" . | nindent 4 }}
spec:
  type: {{ $s.type }}
  ports:
  {{- range or $s.ports (list $s) }}
    - port: {{ .port }}
      targetPort: {{ or .targetPort .port }}
      {{- with .nodePort }}
      nodePort: {{ . }}
      {{- end }}
      protocol: {{ or .protocol "TCP" }}
  {{- end }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
{{- end }}
